src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Harvest_ID__c</fullName>
        <externalId>true</externalId>
        <label>Harvest ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Sync_to_Harvest__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync to Harvest</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/Harvest_Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Harvest Invoices</relationshipLabel>
        <relationshipName>Harvest_Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Created_At__c</fullName>
        <label>Created At</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>United States Dollars - USD</fullName>
                </value>
                <value>
                    <fullName>Euro - EUR</fullName>
                </value>
                <value>
                    <fullName>United Kingdom Pounds - GBP</fullName>
                </value>
                <value>
                    <fullName>Canada Dollars - CAD</fullName>
                </value>
                <value>
                    <fullName>Australia Dollars - AUD</fullName>
                </value>
                <value>
                    <fullName>Japan Yen - JPY</fullName>
                </value>
                <value>
                    <fullName>India Rupees - INR</fullName>
                </value>
                <value>
                    <fullName>New Zealand Dollars - NZD</fullName>
                </value>
                <value>
                    <fullName>Switzerland Francs - CHF</fullName>
                </value>
                <value>
                    <fullName>South Africa Rand - ZAR</fullName>
                </value>
                <value>
                    <fullName>Afghanistan Afghanis - AFN</fullName>
                </value>
                <value>
                    <fullName>Albania Leke - ALL</fullName>
                </value>
                <value>
                    <fullName>Algeria Dinars - DZD</fullName>
                </value>
                <value>
                    <fullName>Argentina Pesos - ARS</fullName>
                </value>
                <value>
                    <fullName>Bahamas Dollars - BSD</fullName>
                </value>
                <value>
                    <fullName>Bahrain Dinars - BHD</fullName>
                </value>
                <value>
                    <fullName>Bangladesh Taka - BDT</fullName>
                </value>
                <value>
                    <fullName>Barbados Dollars - BBD</fullName>
                </value>
                <value>
                    <fullName>Belize Dollar - BZD</fullName>
                </value>
                <value>
                    <fullName>Bermuda Dollars - BMD</fullName>
                </value>
                <value>
                    <fullName>Brazil Reais - BRL</fullName>
                </value>
                <value>
                    <fullName>Bulgaria Leva - BGN</fullName>
                </value>
                <value>
                    <fullName>Chile Pesos - CLP</fullName>
                </value>
                <value>
                    <fullName>China Yuan Renminbi - CNY</fullName>
                </value>
                <value>
                    <fullName>Colombia Pesos - COP</fullName>
                </value>
                <value>
                    <fullName>Costa Rica Colones - CRC</fullName>
                </value>
                <value>
                    <fullName>Croatia Kuna - HRK</fullName>
                </value>
                <value>
                    <fullName>Cyprus Pounds - CYP</fullName>
                </value>
                <value>
                    <fullName>Czech Republic Koruny - CZK</fullName>
                </value>
                <value>
                    <fullName>Dominican Republic Pesos - DOP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Discount_Amount__c</fullName>
        <label>Discount Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <label>Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Due_Amount__c</fullName>
        <label>Due Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Due_At_Human_Format__c</fullName>
        <label>Terms</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Due_At__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Estimate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Estimate</label>
        <referenceTo>Harvest_Estimate__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Harvest_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Harvest_ID__c</fullName>
        <externalId>true</externalId>
        <label>Harvest ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Invoice_No__c</fullName>
        <label>Invoice Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Issued_At__c</fullName>
        <label>Issued At</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Period_End__c</fullName>
        <label>Period End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Period_Start__c</fullName>
        <label>Period Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Purchase_Order__c</fullName>
        <label>Purchase Order</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Partially Paid</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Closed (Written off)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_2_Amount__c</fullName>
        <label>Tax 2 Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tax_2__c</fullName>
        <label>Tax 2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Tax_Amount__c</fullName>
        <label>Tax Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <label>Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Harvest Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Harvest Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Harvest Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Harvest_Invoice_Message__c.object
<CustomObject>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Created_At__c</fullName>
        <label>Created At</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Full_Recipient_List__c</fullName>
        <label>Full Recipient List</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Harvest_ID__c</fullName>
        <externalId>true</externalId>
        <label>Harvest ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Harvest_Invoice__c</referenceTo>
        <relationshipLabel>Invoice Messages</relationshipLabel>
        <relationshipName>Harvest_Invoice_Messages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Send_me_a_copy__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send me a copy</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sent_By_Email__c</fullName>
        <label>Sent By Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Sent_By__c</fullName>
        <label>Sent By</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Harvest Invoice Message</label>
    <nameField>
        <displayFormat>IM-{000000}</displayFormat>
        <label>Harvest Invoice Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Harvest Invoice Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Harvest_Task__c.object
<CustomObject>
    <fields>
        <fullName>Created_at__c</fullName>
        <label>Harvest Record created at</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Default_hourly_rate__c</fullName>
        <label>Default hourly rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Harvest_ID__c</fullName>
        <externalId>true</externalId>
        <label>Harvest ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Harvest Task</label>
    <nameField>
        <label>Harvest Tasks Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Harvest Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Harvest_Task_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Created_at__c</fullName>
        <label>Harvest Record created at</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Estimate__c</fullName>
        <label>Estimate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Harvest_ID__c</fullName>
        <externalId>true</externalId>
        <label>Harvest ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Hourly_rate__c</fullName>
        <label>Hourly rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Harvest Task Assignment</label>
    <nameField>
        <displayFormat>TA-{000000}</displayFormat>
        <label>Harvest Task Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Harvest Task Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Harvest_User__c.object
<CustomObject>
    <fields>
        <fullName>Created_at__c</fullName>
        <label>Harvest Record created at</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Default_hourly_rate__c</fullName>
        <label>Default hourly rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Harvest_ID__c</fullName>
        <externalId>true</externalId>
        <label>Harvest ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Harvest User</label>
    <nameField>
        <label>Harvest User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Harvest People</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Harvest_User_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Created_at__c</fullName>
        <label>Harvest Record created at</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Estimate__c</fullName>
        <label>Estimate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Harvest_ID__c</fullName>
        <externalId>true</externalId>
        <label>Harvest ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Harvest_User__c</fullName>
        <label>Harvest User</label>
        <referenceTo>Harvest_User__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Harvest_User_Assignments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Harvest User Assignment</label>
    <nameField>
        <displayFormat>UA-{000000}</displayFormat>
        <label>Harvest User Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Harvest User Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/HarvestUtil.cls
public class HarvestUtil {
    
    public static Account transformClient(HarvestClient c) {
        Account a = new Account();
        a.Name = c.name;
        a.Harvest_Id__c = c.id;
        a.IsActiveHarvestClient__c = c.active;  
        a.Sync_to_Harvest__c = true;
        return a;
    }
    
    public static Contact transformContact(HarvestContact c, Map<String, Id> accountMap) {
        Contact con = new Contact();
        con.Harvest_Id__c = c.id;
        con.AccountId = accountMap.get(c.clientId); 
        con.FirstName = c.firstname;
        con.LastName = c.lastname;
        con.Email = c.email;
        con.Phone = c.phone;
        con.MobilePhone = c.mobile;
        con.Fax = c.fax;
        con.Sync_to_Harvest__c = true;  
        return con;
    }
    
    public static Harvest_Invoice__c transformInvoice(HarvestInvoice i, Map<String, Id> accountMap) {
        Harvest_Invoice__c hi = new Harvest_Invoice__c();
        hi.Account__c = accountMap.get(i.clientId);
        hi.Amount__c = convertDecimal(i.amount);
        hi.Currency__c = i.currencyName;
        hi.Discount__c = convertDouble(i.discount);
        hi.Discount_Amount__c = convertDecimal(i.discountAmount);
        hi.Due_Amount__c = convertDecimal(i.dueAmount);
        hi.Due_At__c = convertInvoiceDate(i.dueAt);
        hi.Due_At_Human_Format__c = i.dueAtHumanFormat;
        //hi.Estimate__c = i.estimate;
        hi.Harvest_ID__c = i.id;
        hi.Invoice_No__c = i.invoiceNumber;
        hi.Issued_At__c = convertInvoiceDate(i.issuedAt);
        hi.Notes__c = i.notes;
        hi.Period_End__c = convertInvoiceDate(i.periodEnd);
        hi.Period_Start__c = convertInvoiceDate(i.periodStart);
        hi.Purchase_Order__c = i.purchaseOrder;
        hi.State__c = i.state;
        hi.Subject__c = i.subject;
        hi.Tax_2__c = convertDouble(i.tax2);
        hi.Tax_2_Amount__c = convertDecimal(i.taxAmount2);
        hi.Tax__c = convertDouble(i.tax1);
        hi.Tax_Amount__c = convertDecimal(i.taxAmount);
        return hi;
    }

    public static Harvest_Invoice_Message__c transformInvoiceMessage(HarvestInvoiceMessage im, Map<String, Id> invoiceMap) {
        Harvest_Invoice_Message__c him = new Harvest_Invoice_Message__c();
        him.Body__c = im.body;
        him.Created_At__c = convertDateTime(im.createdAt);
        him.Full_Recipient_List__c = im.fullRecipientList;
        him.Harvest_ID__c = im.id;
        him.Invoice__c = invoiceMap.get(im.invoiceId);
        him.Send_me_a_copy__c = im.sendMeACopy; 
        him.Sent_By__c = im.sentBy;
        him.Sent_By_Email__c = im.sentByEmail;
        return him;
    }

    public static Harvest_User__c transformUser(HarvestUser u) {
        Harvest_User__c hu = new Harvest_User__c();
        hu.Name = u.email;
        hu.Default_hourly_rate__c = convertDecimal(u.defaultHourlyRate);
        hu.Department__c = u.department;
        hu.Email__c = u.email;
        hu.First_name__c = u.firstName;
        hu.Harvest_ID__c = u.id;
        hu.Is_Active__c = u.isActive;
        hu.Is_Admin__c = u.isAdmin;
        hu.Is_Contractor__c = u.isContractor;
        hu.Last_name__c = u.lastName;
        hu.Phone__c = u.telephone;
        hu.Timezone__c = u.timeZone;
        return hu;
    }
    
	public static Harvest_Task__c transformTask(HarvestTask t) {
		Harvest_Task__c ht = new Harvest_Task__c();
		ht.Name = t.name;
		ht.Billable_by_default__c = t.billableByDefault;
		ht.Default_hourly_rate__c = convertDouble(t.defaultHourlyRate);
		ht.Harvest_ID__c = t.id;
		ht.Is_default__c = t.isDefault;
		return ht;
	}
    
    public static Harvest_Project__c transformProject(HarvestProject hp, Map<String, Id> accountMap) {
        Harvest_Project__c p = new Harvest_Project__c();
        p.Account__c = accountMap.get(hp.clientId);
        p.Name = hp.name;
        p.Bill_by__c = hp.billBy;
        p.Billable__c = hp.billable;
        if (hp.budget != '') p.Budget__c = Double.valueOf(hp.budget);
        else p.Budget__c = null;    
        p.Budget_by__c = getBudgetBy(hp.budgetBy);
        p.Harvest_ID__c = hp.id;
        p.Notes__c = hp.notes;
        p.Project_Code__c = hp.code;
        p.Active__c = hp.active;
        return p;
    }
    
	public static Harvest_Task_Assignment__c transformTaskAssignment(HarvestTaskAssignment hta, Map<String, Id> projectMap, Map<String, Id> taskMap) {
		Harvest_Task_Assignment__c ta = new Harvest_Task_Assignment__c();
		ta.Billable__c = hta.billable;
		ta.Budget__c = convertDouble(hta.budget);
		ta.Deactivated__c = hta.deactivated;
		ta.Harvest_ID__c = hta.id;
		ta.Hourly_rate__c = convertDouble(hta.hourlyRate);
		ta.Project__c = projectMap.get(hta.projectId);
		ta.Task__c = taskMap.get(hta.taskId);
		return ta;
	}
	
	public static Harvest_User_Assignment__c transformUserAssignment(HarvestUserAssignment hua, Map<String, Id> projectMap, Map<String, Id> userMap) {
		Harvest_User_Assignment__c ua = new Harvest_User_Assignment__c();
		ua.Harvest_ID__c = hua.id;
		ua.Harvest_User__c = userMap.get(hua.userid);
		ua.Hourly_rate__c = convertDecimal(hua.hourlyRate);
		ua.Is_Deactivated__c = hua.deactivated;
		ua.Is_Project_Manager__c = hua.isProjectManager;
		ua.Project__c = projectMap.get(hua.projectId);
		return ua;
	}
    
    public static Double convertDouble(String s) {
        if (s == '' || s == null)
            return null;
        else
            return Double.valueOf(s);
    }
    
    public static Decimal convertDecimal(String s) {
        if (s == '' || s == null)
            return null;
        else
            return Decimal.valueOf(s);
    }
    
    public static String getBudgetBy(String value) {
        if (value == '')
            return 'none';
        else if (value == 'No Budget')
            return 'none';
        else if (value == 'Total Project Hours')
            return 'project';
        else if (value == 'Total Project Fees')
            return 'project_cost';
        else if (value == 'Hours per task')
            return 'task';
        else if (value == 'Hours per person')
            return 'person';
        else if (value == 'none')
            return 'No Budget';
        else if (value == 'project')
            return 'Total Project Hours';
        else if (value == 'project_cost')
            return 'Total Project Fees';
        else if (value == 'task')
            return 'Hours per task';
        else if (value == 'person')
            return 'Hours per person';
        else
            return '';          
    }
    
    public static Map<String, Id> getHarvestAccountMap(set<String> clientIds) {
        Map<String, Id> returnMap = new Map<String, Id>();      
        for (Account a : [Select Id, Harvest_Id__c from Account where Harvest_Id__c in :clientIds]) {
            returnMap.put(a.Harvest_Id__c, a.Id);
        }
        return returnMap;
    }
    
    public static Map<String, Id> getHarvestProjectMap(set<String> projectIds) {
        Map<String, Id> returnMap = new Map<String, Id>();      
        for (Harvest_Project__c p : [Select Id, Harvest_Id__c from Harvest_Project__c where Harvest_Id__c in :projectIds]) {
            returnMap.put(p.Harvest_Id__c, p.Id);
        }
        return returnMap;
    }
            
    public static String getBillBy(String value) {
        if (value == null)
            return 'none';
        else
            return value;
    }
    
    public static Boolean convertBoolean(String bool) {
        if (bool == 'true')
            return true;
        else
            return false;
    }
    
    public static Date convertInvoiceDate(String s) {
        if (s == '' || s == null) {
            return null;
        } else {
            String[] dateArray = s.split('-');
            return Date.newInstance(Integer.valueOf(dateArray[0]), Integer.valueOf(dateArray[1]), Integer.valueOf(dateArray[2]));
        }
    }
    
    public static DateTime convertDateTime(String s) {
        if (s == '' || s == null) {
            return null;
        } else {
            String year = s.substring(0, 4);
            String month = s.substring(5, 7);
            String day = s.substring(8, 10);
            String hours = s.substring(11, 13);
            String minutes = s.substring(14, 16);
            String seconds = s.substring(17, 19);
            return DateTime.newInstanceGmt(
                Integer.valueOf(year), 
                Integer.valueOf(month), 
                Integer.valueOf(day), 
                Integer.valueOf(hours), 
                Integer.valueOf(minutes), 
                Integer.valueOf(seconds)
            );
        }
    }   
        
}