src/objects/Harvest_Task__c.object
<CustomObject>
    <fields>
        <fullName>Harvest_ID__c</fullName>
        <externalId>true</externalId>
        <label>Harvest ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Harvest Task</label>
    <nameField>
        <label>Harvest Tasks Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Harvest Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Harvest_Task_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Harvest_ID__c</fullName>
        <externalId>true</externalId>
        <label>Harvest ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Harvest Task Assignment</label>
    <nameField>
        <displayFormat>TA-{000000}</displayFormat>
        <label>Harvest Task Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Harvest Task Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Harvest_Time_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Harvest_Id__c</fullName>
        <externalId>true</externalId>
        <label>Harvest ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Harvest Time Entry</label>
    <nameField>
        <displayFormat>TE-{000000}</displayFormat>
        <label>Harvest Time Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Harvest Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Harvest_User__c.object
<CustomObject>
    <fields>
        <fullName>Harvest_ID__c</fullName>
        <externalId>true</externalId>
        <label>Harvest ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Harvest User</label>
    <nameField>
        <label>Harvest User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Harvest People</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Harvest_User_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Harvest_ID__c</fullName>
        <externalId>true</externalId>
        <label>Harvest ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Harvest_User__c</fullName>
        <label>Harvest User</label>
        <referenceTo>Harvest_User__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Harvest_User_Assignments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Harvest User Assignment</label>
    <nameField>
        <displayFormat>UA-{000000}</displayFormat>
        <label>Harvest User Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Harvest User Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/HarvestProjectSync.cls
/*
global class HarvestProjectSync {
    
    webService static String refreshProject(String projectId) {     
        Harvest h = new Harvest();
        HarvestProject p = h.getProject(projectId);
                
        Harvest_Project__c hp = [Select Id, Harvest_Id__c, Account__c, Account__r.Harvest_Id__c from Harvest_Project__c where Harvest_Id__c = :projectId];
        Map<String, Id> accountMap = new Map<String, Id> { hp.Account__r.Harvest_Id__c => hp.Account__c };
        Map<String, Id> projectMap = new Map<String, Id> { hp.Harvest_Id__c => hp.Id };

        hp = HarvestUtil.transformProject(p, accountMap);           
        upsert hp Harvest_Id__c; 
        return null;
    }
}
*/
 
global class HarvestProjectSync {
	
	webService static String refreshProject(String projectId) {		
		Harvest h = new Harvest();
		/*DO CALLOUTS*/
		HarvestProject p = h.getProject(projectId); 
		List<HarvestTaskAssignment> hTaskAssignments = h.getTaskAssignments(projectId);
		List<HarvestUserAssignment> hUserAssignments = h.getUserAssignments(projectId);
		List<HarvestTImeEntry> hTimeEntries = h.getTimeEntriesForProject(projectId, Date.today().addDays(-31), Date.today());
		
		/*PROCESS PROJECT*/
		Harvest_Project__c hp = [Select Id, Harvest_Id__c, Account__c, Account__r.Harvest_Id__c from Harvest_Project__c where Harvest_Id__c = :projectId];
		Map<String, Id> accountMap = new Map<String, Id> { hp.Account__r.Harvest_Id__c => hp.Account__c };
		Map<String, Id> projectMap = new Map<String, Id> { hp.Harvest_Id__c => hp.Id };

		hp = HarvestUtil.transformProject(p, accountMap);
		
		/*PROCESS TASK ASSIGNMENTS*/
		Map<String, Id> taskMap = new Map<String, Id>();
		Set<String> taskIds = new Set<String>();
		List<Harvest_Task_Assignment__c> taskAssignments = new List<Harvest_Task_Assignment__c>();
		
		for (HarvestTaskAssignment ta : hTaskAssignments) {
			taskIds.add(ta.taskId);
		}
		
		for (Harvest_Task__c t : [Select Id, Harvest_Id__c from Harvest_Task__c where Harvest_Id__c in :taskIds]) {
			taskMap.put(t.Harvest_Id__c, t.Id);
		}

		for (HarvestTaskAssignment ta : hTaskAssignments){
			taskAssignments.add(HarvestUtil.transformTaskAssignment(ta, projectMap, taskMap));
		}
		/*PROCESS USER ASSIGNMENTS*/
		Map<String, Id> userMap = new Map<String, Id>();
		Set<String> userIds = new Set<String>();
		List<Harvest_User_Assignment__c> userAssignments = new List<Harvest_User_Assignment__c>();

		for (HarvestUserAssignment ua : hUserAssignments) {
			userIds.add(ua.userId);
		}

		for (HarvestTImeEntry ht : hTimeEntries) {
			userIds.add(ht.userId);
		}
		
		for (Harvest_User__c u : [Select Id, Harvest_Id__c from Harvest_User__c where Harvest_Id__c in :userIds]){
			userMap.put(u.Harvest_Id__c, u.Id);
		}

		for (HarvestUserAssignment ua : hUserAssignments) {
	 		userAssignments.add(HarvestUtil.transformUserAssignment(ua, projectMap, userMap));
		}

		/* PROCESS TIME ENTRIEs
		*/
		List<Harvest_Time_Entry__c> timeEntries = new List<Harvest_Time_Entry__c>();

		for (HarvestTImeEntry ht : hTimeEntries) {
			timeEntries.add(HarvestUtil.transformTimeEntry(ht, userMap, taskMap, accountMap, projectMap));
		}
		
			
		upsert hp Harvest_Id__c; 
		upsert taskAssignments Harvest_Id__c;
		upsert userAssignments Harvest_Id__c;
		upsert timeEntries Harvest_Id__c; 
		
		return null;
	}
}