src/objects/Harvest_Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Harvest Invoices</relationshipLabel>
        <relationshipName>Harvest_Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Harvest_ID__c</fullName>
        <externalId>true</externalId>
        <label>Harvest ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Harvest Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Harvest Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Harvest Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Harvest_Invoice_Message__c.object
<CustomObject>
    <fields>
        <fullName>Harvest_ID__c</fullName>
        <externalId>true</externalId>
        <label>Harvest ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Harvest Invoice Message</label>
    <nameField>
        <displayFormat>IM-{000000}</displayFormat>
        <label>Harvest Invoice Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Harvest Invoice Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/HarvestInvoiceSync.cls
global class HarvestInvoiceSync {   
    
    webservice static String refreshInvoice(String invoiceId) {
    
        Harvest h = new Harvest();
        /*DO CALLOUTS*/
        HarvestInvoice i = h.getInvoice(invoiceId);
        List<HarvestInvoiceMessage> hInvoiceMessages = h.getInvoiceMessages(invoiceId);

        /*PROCESS INVOICE*/ 
        Harvest_Invoice__c hi = [Select Id, Harvest_Id__c, Account__r.Harvest_Id__c, Account__c from Harvest_Invoice__c where Harvest_Id__c = :invoiceId];
        Map<String, Id> accountMap = new Map<String, Id> { hi.Account__r.Harvest_Id__c => hi.Account__c };
        Map<String, Id> invoiceMap = new Map<String, Id> { hi.Harvest_Id__c => hi.Id };
        hi = HarvestUtil.transformInvoice(i, accountMap); 
        
        /*PROCESS INVOICE MESSAGES*/ 
        List<Harvest_Invoice_Message__c> invoiceMessages = new List<Harvest_Invoice_Message__c>();
        for (HarvestInvoiceMessage im : hInvoiceMessages)
            invoiceMessages.add(HarvestUtil.transformInvoiceMessage(im, invoiceMap));
        
        /*PROCESS INVOICE LINES*/
   		/*TODO*/
        
        upsert hi Harvest_Id__c;
        upsert invoiceMessages Harvest_Id__c;
        return null;
    }
    
    
}