src/objects/Harvest__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>CronTriggerId__c</fullName>
        <label>CronTriggerId</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Harvest</label>
</CustomObject>

src/classes/HarvestInboundScheduler.cls
global class HarvestInboundScheduler {
    
    global void HarvestInboundScheduler() {  }
 
    public static void start() {
        //Seconds Minutes Hours Day_of_month Month Day_of_week optional_year
        String jobId = System.schedule('Harvest Inbound Sync', '0 0 1-23 * * ?', new HarvestInboundSync());
        Harvest__c settings = Harvest__c.getOrgDefaults(); 
        settings.CronTriggerId__c = jobId;
        upsert settings; 
    }
    
}